[2025-04-05T13:55:47.851886+02:00] request.INFO: Matched route "app_admin_translations_table". {"route":"app_admin_translations_table","route_parameters":{"_route":"app_admin_translations_table","_controller":"App\\Controller\\TranslationController::table","table":"user"},"request_uri":"https://serveur.dmqode.be/admin/translations/table/user","method":"GET"} []
[2025-04-05T13:55:47.858163+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T13:55:47.858220+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:47.858262+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:47.858298+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:47.858335+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:47.859735+02:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/serveur/vendor/symfony/security-http/Firewall/AccessListener.php:83)"} []
[2025-04-05T13:55:47.860067+02:00] security.DEBUG: Calling Authentication entry point. {"entry_point":{"App\\Security\\LoginFormAuthenticator":[]}} []
[2025-04-05T13:55:47.936089+02:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://serveur.dmqode.be/login","method":"GET"} []
[2025-04-05T13:55:47.937174+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T13:55:47.937226+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:47.937264+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:47.937297+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:47.937329+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:56.557161+02:00] request.INFO: Matched route "app_forgot_password_request". {"route":"app_forgot_password_request","route_parameters":{"_route":"app_forgot_password_request","_controller":"App\\Controller\\ResetPasswordController::request"},"request_uri":"https://serveur.dmqode.be/reset-password","method":"GET"} []
[2025-04-05T13:55:56.558929+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T13:55:56.558985+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:56.559030+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:56.559069+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:55:56.559125+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:56:03.433398+02:00] request.INFO: Matched route "app_forgot_password_request". {"route":"app_forgot_password_request","route_parameters":{"_route":"app_forgot_password_request","_controller":"App\\Controller\\ResetPasswordController::request"},"request_uri":"https://serveur.dmqode.be/reset-password","method":"POST"} []
[2025-04-05T13:56:03.435141+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T13:56:03.435196+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:56:03.435390+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:56:03.435437+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:56:03.435485+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T13:56:03.440160+02:00] request.DEBUG: CSRF validation accepted using origin info. [] []
[2025-04-05T13:56:03.529212+02:00] request.CRITICAL: Uncaught PHP Exception Error: "Call to undefined method App\Entity\ResetPasswordRequest::setExpiresAt()" at ResetPasswordRequestRepository.php line 49 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Entity\\ResetPasswordRequest::setExpiresAt() at /var/www/serveur/src/Repository/ResetPasswordRequestRepository.php:49)"} []
[2025-04-05T15:08:46.162987+02:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"https://serveur.dmqode.be/","method":"GET"} []
[2025-04-05T15:08:46.165914+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T15:08:46.166004+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T15:08:46.166084+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T15:08:46.166156+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T15:08:46.166246+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T15:54:03.187427+02:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://serveur.dmqode.be/login","method":"GET"} []
[2025-04-05T15:54:03.189037+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T15:54:03.189089+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T15:54:03.189132+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T15:54:03.189182+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T15:54:03.189221+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.773311+02:00] request.INFO: Matched route "app_admin_email_template_new". {"route":"app_admin_email_template_new","route_parameters":{"_route":"app_admin_email_template_new","_controller":"App\\Controller\\EmailTemplateController::new"},"request_uri":"https://serveur.dmqode.be/admin/email-templates/new","method":"GET"} []
[2025-04-05T16:42:04.778091+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T16:42:04.778150+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.778196+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.778237+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.778277+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.779231+02:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/serveur/vendor/symfony/security-http/Firewall/AccessListener.php:83)"} []
[2025-04-05T16:42:04.779326+02:00] security.DEBUG: Calling Authentication entry point. {"entry_point":{"App\\Security\\LoginFormAuthenticator":[]}} []
[2025-04-05T16:42:04.833585+02:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://serveur.dmqode.be/login","method":"GET"} []
[2025-04-05T16:42:04.834488+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T16:42:04.834539+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.834581+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.834618+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:04.834655+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:12.452584+02:00] request.INFO: Matched route "app_forgot_password_request". {"route":"app_forgot_password_request","route_parameters":{"_route":"app_forgot_password_request","_controller":"App\\Controller\\ResetPasswordController::request"},"request_uri":"https://serveur.dmqode.be/reset-password","method":"GET"} []
[2025-04-05T16:42:12.454236+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T16:42:12.454289+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:12.454328+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:12.454362+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:12.454395+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:17.827838+02:00] request.INFO: Matched route "app_forgot_password_request". {"route":"app_forgot_password_request","route_parameters":{"_route":"app_forgot_password_request","_controller":"App\\Controller\\ResetPasswordController::request"},"request_uri":"https://serveur.dmqode.be/reset-password","method":"POST"} []
[2025-04-05T16:42:17.829462+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2025-04-05T16:42:17.829513+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:17.829698+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:17.829737+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:17.829789+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2025-04-05T16:42:17.833985+02:00] request.DEBUG: CSRF validation accepted using origin info. [] []
[2025-04-05T16:42:17.846801+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0_.created_at' in 'field list'" at ExceptionConverter.php line 67 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 1054): An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0_.created_at' in 'field list' at /var/www/serveur/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:67)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1054): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0_.created_at' in 'field list' at /var/www/serveur/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:24)\n[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r0_.created_at' in 'field list' at /var/www/serveur/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []
